In [67]:
#Quiz 1

In [68]:
#1. Crea un diccionario que contenga 3 llaves que sean de tipo string y cuyos valores sean una lista que contenga 5 valores (3 numéricos y 2 flotantes)
nadadores = {"Eugenio": [3, 2, 4, 21.2, 21.7],
             "Emilio": [2, 4, 5, 20.9, 21.5],
             "Enrique": [4, 6, 5, 19.9, 20.1]}

In [69]:
#2. A partir del diccionario anterior, muestra a sus ítems. ¿Qué tipo de objeto se obtiene?
nadadores.items()

dict_items([('Eugenio', [3, 2, 4, 21.2, 21.7]), ('Emilio', [2, 4, 5, 20.9, 21.5]), ('Enrique', [4, 6, 5, 19.9, 20.1])])

In [73]:
#3. Crea un panel de datos usando tu diccionario.
Nadadores = pd.DataFrame({"Eugenio": [3, 2, 4, 21.2, 21.7],
             "Emilio": [2, 4, 5, 20.9, 21.5],
             "Enrique": [4, 6, 5, 19.9, 20.1]}, index = ["Número de veces nadadas", "Competencias ganadas", "Años nadando", "1er Tiempo", "2ndo Tiempo"])
Nadadores =pd.DataFrame(Nadadores)
Nadadores

                         Eugenio  Emilio  Enrique
Número de veces nadadas      3.0     2.0      4.0
Competencias ganadas         2.0     4.0      6.0
Años nadando                 4.0     5.0      5.0
1er Tiempo                  21.2    20.9     19.9
2ndo Tiempo                 21.7    21.5     20.1

In [74]:
print (Nadadores)

                         Eugenio  Emilio  Enrique
Número de veces nadadas      3.0     2.0      4.0
Competencias ganadas         2.0     4.0      6.0
Años nadando                 4.0     5.0      5.0
1er Tiempo                  21.2    20.9     19.9
2ndo Tiempo                 21.7    21.5     20.1

In [75]:
type (Nadadores)

pandas.core.frame.DataFrame

In [77]:
#Realiza tres segregaciones distintas
Nadadores.iloc[0:3]

                         Eugenio  Emilio  Enrique
Número de veces nadadas      3.0     2.0      4.0
Competencias ganadas         2.0     4.0      6.0
Años nadando                 4.0     5.0      5.0

In [78]:
Nadadores[["Eugenio", "Enrique"]]

                         Eugenio  Enrique
Número de veces nadadas      3.0      4.0
Competencias ganadas         2.0      6.0
Años nadando                 4.0      5.0
1er Tiempo                  21.2     19.9
2ndo Tiempo                 21.7     20.1

In [79]:
Nadadores.iloc[3]

Eugenio    21.2
Emilio     20.9
Enrique    19.9
Name: 1er Tiempo, dtype: float64

In [80]:
# 4.Realiza un breve análisis descriptivo de tu panel de datos. Explica los valores que obtienes
Nadadores.describe()

         Eugenio     Emilio    Enrique
count   5.000000   5.000000   5.000000
mean   10.380000  10.680000  11.000000
std    10.131732   9.666282   8.246514
min     2.000000   2.000000   4.000000
25%     3.000000   4.000000   5.000000
50%     4.000000   5.000000   6.000000
75%    21.200000  20.900000  19.900000
max    21.700000  21.500000  20.100000

In [86]:
# 5. Realiza dos filtros de búsqueda sobre tu panel de datos
#Valor mínimo de la columna Enrique
minimo = Nadadores["Enrique"].min()
minimo

4.0

In [87]:
#Valor máximo de la columna Eugenio
maximo = Nadadores["Eugenio"].max()
maximo

21.7