#Tarea 2

In [4]:
Tiempos = {"Jimena" : [1.2, 1.5, .9, 1.0, 1.4, 1.9, 1.0, 2.0, 1.3, 1.6],
           "Carlos" : [1.6, 1.9, 1.7, 1.8, 1.2, 2.0, 2.2, 1.9, 1.8, 2.0],
           "Rocio" : [1.7, 1.2, 1.8, 1.6, 2.1, 2.0, 1.9, 1.8, 1.2, 1.9],
           "Felipe" : [1.2, 1.9, 1.2, 1.3, 1.4, 1.4, 1.5, 1.4, 1.4, 1.7],
           "Paulina" : [1.3, 1.2, 1.4, 1.3, 1.3, 1.2, 1.8, 1.5, 1.6, 1.9],
           "Leonardo" : [1.2, 1.2, 1.4, 1.1, 1.8, 1.2, 1.4, 1.2, 1.2, 1.3],
           "María" : [1.2, 1.4, 1.3, 1.2, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3],
           "Ricardo" : [1.3, 1.4, 1.3, 1.5, 1.6, 1.3, 1.3, 1.5, 1.6, 1.5],
           "Gerardo" : [1.4, 1.7, 1.9, 2.0, 2.3, 2.4, 2.0, 2.1, 1.9, 1.8],
           "Lucía": [1.3, 1.6, 1.4, 1.5, 1.2, 1.1, 1.2, 1.3, 1.4, 1.3]}

In [5]:
print (Tiempos)

{'Jimena': [1.2, 1.5, 0.9, 1.0, 1.4, 1.9, 1.0, 2.0, 1.3, 1.6], 'Carlos': [1.6, 1.9, 1.7, 1.8, 1.2, 2.0, 2.2, 1.9, 1.8, 2.0], 'Rocio': [1.7, 1.2, 1.8, 1.6, 2.1, 2.0, 1.9, 1.8, 1.2, 1.9], 'Felipe': [1.2, 1.9, 1.2, 1.3, 1.4, 1.4, 1.5, 1.4, 1.4, 1.7], 'Paulina': [1.3, 1.2, 1.4, 1.3, 1.3, 1.2, 1.8, 1.5, 1.6, 1.9], 'Leonardo': [1.2, 1.2, 1.4, 1.1, 1.8, 1.2, 1.4, 1.2, 1.2, 1.3], 'María': [1.2, 1.4, 1.3, 1.2, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3], 'Ricardo': [1.3, 1.4, 1.3, 1.5, 1.6, 1.3, 1.3, 1.5, 1.6, 1.5], 'Gerardo': [1.4, 1.7, 1.9, 2.0, 2.3, 2.4, 2.0, 2.1, 1.9, 1.8], 'Lucía': [1.3, 1.6, 1.4, 1.5, 1.2, 1.1, 1.2, 1.3, 1.4, 1.3]}

In [6]:
import pandas as pd

In [8]:
Tabla = pd.DataFrame(Tiempos)
Tabla

,Jimena,Carlos,Rocio,Felipe,Paulina,Leonardo,María,Ricardo,Gerardo,Lucía
0,1.2,1.6,1.7,1.2,1.3,1.2,1.2,1.3,1.4,1.3
1,1.5,1.9,1.2,1.9,1.2,1.2,1.4,1.4,1.7,1.6
2,0.9,1.7,1.8,1.2,1.4,1.4,1.3,1.3,1.9,1.4
3,1.0,1.8,1.6,1.3,1.3,1.1,1.2,1.5,2.0,1.5
4,1.4,1.2,2.1,1.4,1.3,1.8,1.4,1.6,2.3,1.2
5,1.9,2.0,2.0,1.4,1.2,1.2,1.5,1.3,2.4,1.1
6,1.0,2.2,1.9,1.5,1.8,1.4,1.2,1.3,2.0,1.2
7,2.0,1.9,1.8,1.4,1.5,1.2,1.3,1.5,2.1,1.3
8,1.3,1.8,1.2,1.4,1.6,1.2,1.4,1.6,1.9,1.4
9,1.6,2.0,1.9,1.7,1.9,1.3,1.3,1.5,1.8,1.3

In [10]:
type (Tabla)

pandas.core.frame.DataFrame

In [11]:
Tabla.ndim

2

In [12]:
Tabla["Gerardo"]

0    1.4
1    1.7
2    1.9
3    2.0
4    2.3
5    2.4
6    2.0
7    2.1
8    1.9
9    1.8
Name: Gerardo, dtype: float64

In [13]:
Tabla.iloc[0:4]

,Jimena,Carlos,Rocio,Felipe,Paulina,Leonardo,María,Ricardo,Gerardo,Lucía
0,1.2,1.6,1.7,1.2,1.3,1.2,1.2,1.3,1.4,1.3
1,1.5,1.9,1.2,1.9,1.2,1.2,1.4,1.4,1.7,1.6
2,0.9,1.7,1.8,1.2,1.4,1.4,1.3,1.3,1.9,1.4
3,1.0,1.8,1.6,1.3,1.3,1.1,1.2,1.5,2.0,1.5

In [15]:
Tabla [["Rocio", "Paulina"]]

   Rocio  Paulina
0    1.7      1.3
1    1.2      1.2
2    1.8      1.4
3    1.6      1.3
4    2.1      1.3
5    2.0      1.2
6    1.9      1.8
7    1.8      1.5
8    1.2      1.6
9    1.9      1.9

In [16]:
Tabla.iloc[5]

Jimena      1.9
Carlos      2.0
Rocio       2.0
Felipe      1.4
Paulina     1.2
Leonardo    1.2
María       1.5
Ricardo     1.3
Gerardo     2.4
Lucía       1.1
Name: 5, dtype: float64